### PR TITLE
Add a responsive nav menu

### PR DESCRIPTION
**Pull request by compiuta**
**- Summary**
In this pull request I have added a responsive nav requested in issue #272 

When using the site on mobile devices the nav menu would scroll horizontally instead of changing into a mobile responsive menu with a hamburger icon button.

**- Test plan**

nav-after-1
nav-after-2

**- Description for the changelog**
Add a responsive nav menu.

**- A picture of a cute animal (not mandatory but encouraged)**

baby-chicken

### CODE REVIEW

**Comment by raphink** [comment]
This works for me. It would be great to merge it, as it's a much better solution than the horizontal swiping.

**Comment by cameronelliott** [comment]
@raphink @erquhart 
I am also looking for this feature, and support merging, if everything looks reasonable.
Thank you, @compiuta

**Comment by Gioele-Bencivenga** [comment]
fantastic addition, should be the default, still works perfectly

**Comment by lwuite** [comment]
Merging this into my fork didnt work because of merge issues but just copying and pasting the logic worked perfect. This should be the default. Thank you @compiuta.

**Pull request merged**
